name: 'Move model from dev/test to test/prod'

on:
  workflow_dispatch:
    inputs:
      model_name:
        description: 'Model Name'
        required: true
      source_workspace:
        description: 'Model source workspace name'
        required: true
      source_resource_group:
        description: 'Model source resource group'
        required: true
      destination_workspace:
        description: 'Model destination workspace'
        required: true
      destination_resource_group:
        description: 'Model destination resource group'
        required: true
      destination_model_tag:
        description: 'Model tag in destination'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Check Out Repository
      uses: actions/checkout@v2

    - name: Azure source login
      uses: azure/login@v1.2.4
      with:
          creds: ${{ secrets.AZURE_DEV_CREDENTIALS }}        

    - name: Download model from source and register in destination
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          az account show
          #az extension add -n azure-cli-ml
          MODEL=$(az ml model list --model-name ${{github.event.inputs.model_name}} --resource-group ${{github.event.inputs.source_resource_group}} --workspace-name ${{github.event.inputs.source_workspace}} -l -otsv --query '[].{i:id}' | tr -d '\r')
          az ml model download --model-id $MODEL --target-dir . --workspace-name ${{github.event.inputs.source_workspace}} --resource-group ${{github.event.inputs.source_resource_group}}

    - name: Azure destination login
      uses: azure/login@v1.2.4
      with:
        creds: ${{ secrets.AZURE_TEST_CREDENTIALS }}

    - name: Register model in destination workspace
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          az ml model register -n ${{github.event.inputs.model_name}} -p ./*.pkl --workspace-name ${{github.event.inputs.destination_workspace}} --resource-group ${{github.event.inputs.destination_resource_group}} --tag ${{github.event.inputs.destination_model_tag}}
